export default {
  common: {
    rental: 'Rental Now',
    popular: 'Popular Car',
    recommend: 'Recommendation Car',
    viewAll: 'View All',
    viewLess: 'View Less',
    showMore: 'Show more car',
    cars: 'cars',
    location: 'Location',
    date: 'Date',
    time: 'Time',
    day: 'days',
    showAll: 'Show all',
    showLess: 'Show less',
    person: 'Person',
    listCarEmpty: 'List of cars are empty',
    review: 'Reviewer',
    pickUp: 'Pick-Up',
    dropOff: 'Drop-Off',
    type: 'TYPE',
    capacity: 'CAPACITY',
    price: 'PRICE',
    orMore: 'or More',
  },
  header: {
    placeHolder: 'Search something here',
    analytics: 'Analytics',
    security: 'Security',
    logout: 'Logout',
  },
  footer: {
    about: 'About',
    socials: 'Socials',
    community: 'Community',
  },
  detail: {
    review: 'Review',
    typeCar: 'Type Car',
    capacity: 'Capacity',
    steering: 'Manual',
    gasoline: 'Gasoline',
    reviewEmpty: "Don't have any review",
  },
  rental: {
    summary: {
      title: 'Rental Summary',
      subTitle:
        'Prices may change depending on the length of the rental and the price of your rental car.',
      subtotal: 'Subtotal',
      tax: 'Tax',
      totalSummary: 'Rental Summary',
      subSummary: 'Overall price rental',
      subSummarySecond: 'Overall price and includes rental discount',
    },
    billingInfo: {
      title: 'Billing Info',
      subTitle: 'Please enter your billing info',
      name: 'Name',
      namePlaceHolder: 'Your name',
      address: 'Address',
      phoneNumber: 'Phone Number',
      city: 'Town / City',
    },
    rentalInfo: {
      title: 'Rental Info',
      subTitle: 'Please select your rental date',
      location: 'Location',
      locationPlaceHolder: 'Select your city',
      time: 'Time',
      timePlaceHolder: 'Select your time',
      date: 'Date',
      datePlaceHolder: 'Select your date',
    },
    paymentMethod: {
      title: 'Payment Method',
      subTitle: 'Please enter your payment method',
    },
    confirmation: {
      title: 'Confirmation',
      subTitle: 'We are getting to the end. Just few clicks and your rental is ready!',
      confirmOne: 'I agree with sending an Marketing and newsletter emails. No spam, promised!',
      confirmTwo: 'I agree with our terms and conditions and privacy policy.',
    },
  },
};
