export default {
  common: {
    rental: 'Thuê xe',
    popular: 'Phổ biến',
    recommend: 'Đề xuất',
    viewAll: 'Nhiều hơn',
    viewLess: 'Ít hơn',
    showMore: 'Nhiều hơn',
    cars: 'xe',
    location: 'Địa điểm',
    date: 'Ngày',
    time: 'Thời gian',
    day: 'ngày',
    showAll: 'Tất cả',
    showLess: 'Ít hơn',
    person: 'Người',
    listCarEmpty: 'Danh sách xe rỗng',
    review: 'Đánh giá',
    pickUp: 'Nhận xe',
    dropOff: 'Trả xe',
    type: 'LOẠI XE',
    capacity: 'SỐ GHẾ',
    price: 'GIÁ',
    orMore: 'hoặc nhiều hơn',
  },
  header: {
    placeHolder: 'Tìm kiếm',
    analytics: 'Phân tích',
    security: 'Bảo mật',
    logout: 'Đăng xuất',
  },
  footer: {
    about: 'Về chúng tôi',
    socials: 'Xã hội',
    community: 'Cộng đồng',
  },
  detail: {
    review: 'Đánh giá',
    typeCar: 'Loại xe',
    capacity: 'Sức chứa',
    steering: 'Hệ thống lái',
    gasoline: 'Dung tích',
    reviewEmpty: 'Không có lượt đánh giá',
  },
  rental: {
    summary: {
      title: 'Tóm tắt',
      subTitle:
        'Giá có thể thay đổi tùy thuộc vào thời gian cho thuê và giá của chiếc xe cho thuê của bạn.',
      subtotal: 'Giá',
      tax: 'Thuế',
      totalSummary: 'Tổng giá thuê xe',
      subSummary: 'Tổng giá cho thuê',
      subSummarySecond: 'Tổng giá cho thuê đã bao gồm thuế',
    },
    billingInfo: {
      title: 'Thông tin thánh toán',
      subTitle: 'Vui lòng nhập thông tin thánh toán',
      name: 'Tên',
      namePlaceHolder: 'Tên của bạn',
      address: 'Địa chỉ',
      phoneNumber: 'Số điện thoại',
      city: 'Thành phố',
    },
    rentalInfo: {
      title: 'Thông tin cho thuê',
      subTitle: 'Vui lòng nhập ngày cho thuê',
      location: 'Địa điểm',
      locationPlaceHolder: 'Chọn thành phố',
      time: 'Thời gian',
      timePlaceHolder: 'Chọn thời gian',
      date: 'Ngày',
      datePlaceHolder: 'Chọn ngày',
    },
    paymentMethod: {
      title: 'Phương thức thanh toán',
      subTitle: 'Vui lòng nhập phương thức thanh toán',
    },
    confirmation: {
      title: 'Xác nhận',
      subTitle: 'Gần xong rồi. Hãy nhấp vào xác nhận và việc cho thuê xe của bạn đã sẵn sàng',
      confirmOne:
        'Tôi đồng ý với việc gửi một email tiếp thị và bản tin. Không có thư rác, hứa hẹn!',
      confirmTwo: 'Tôi đồng ý với điều khoản, điều kiện và chính sách bảo mật',
    },
  },
};
